name: Deploy Firebase Functions

'on':
  push:
    branches:
      - Action_Tests
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICARAGUA_PROJECT }}'
          projectId: nicaragua-project
          target: nicaragua-api
      - name: Install Firebase tools
        run: npm install -g firebase-tools
        working-directory: "."
      - name: Download Backend Deps
        working-directory: "."
        run: npm install
      - name: Deploy Firebase Functions
        env:
          JWT_TOKEN: '${{ secrets.JWT_TOKEN }}'
          NOTIFICATION_TOKEN: '${{ secrets.NOTIFICATION_TOKEN }}'
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase-tools deploy --only functions
