name: Deploy Firebase Functions

'on':
  push:
    branches:
      - Action_Tests
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Json File
        working-directory: "."
        run: echo ${{ secrets.GITHUB_TOKEN }} >> $HOME/config.json | cat $HOME/config.json
      - uses: actions/checkout@v2
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICARAGUA_PROJECT }}'
          projectId: nicaragua-project
          target: nicaragua-api
          
      - name: Download Backend Deps
        working-directory: "."
        run: npm install
      - name: Deploy Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
