name: Deploy Firebase Functions

'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    concurrency: production
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICARAGUA_PROJECT }}'
          projectId: nicaragua-project
          target: nicaragua-api
      - name: Show Secret
        run : |
          echo $AWS_PINPOINT_ACCESS_KEY 
        env:
          AWS_PINPOINT_ACCESS_KEY: '${{secrets.AWS_PINPOINT_ACCESS_KEY}}'
      - name: Show Variable
        run : |
          echo $PROJECT_ID 
        env:
          PROJECT_ID: '${{secrets.PROJECT_ID}}'
      - name: Install Firebase tools
        run: npm install -g firebase-tools
        working-directory: "."
      - name: Download Backend Deps
        working-directory: "."
        run: npm install
      - name: Deploy Firebase Functions
        env:
          JWT_TOKEN: '${{ secrets.JWT_TOKEN }}'
          NOTIFICATION_TOKEN: '${{ secrets.NOTIFICATION_TOKEN }}'
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          AWS_REGION: '${{ vars.AWS_REGION }}'
          ORIGINATION_NUMBER : '${{ vars.NOTIFICATION_TOKEN }}'
          PROJECT_ID: '${{vars.PROJECT_ID}}'
          AWS_PINPOINT_ACCESS_KEY: '${{secrets.AWS_PINPOINT_ACCESS_KEY}}'
          AWS_PINPOINT_SECRET : '${{secrets.AWS_PINPOINT_SECRET}}'
          ENVIRONMENT: ${{vars.ENVIRONMENT}} 
        run: npx firebase-tools deploy --only functions
