name: Deploy Firebase Functions

'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICARAGUA_PROJECT }}'
          projectId: nicaragua-project
          target: nicaragua-api
          
      - name: Download Backend Deps
        working-directory: "."
        run: npm install
      - name: Deploy Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          ards: deploy --only functions
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NICARAGUA_PROJECT }}
